import { type NextPage } from "next";
import Head from "next/head";
import { api, type RouterOutputs } from "~/utils/api";
import { SignIn, SignInButton } from "@clerk/nextjs";
import { useUser } from "@clerk/nextjs";
import Image from "next/image";

const CreatePostWizard = () => {
  const { user } = useUser()
  if (!user) return null
  console.log(user)
  return (
    <div className="border-b border-slate-400 flex gap-3 p-4">
      <Image width={50} height={50} src={user?.profileImageUrl} className="rounded-full" alt="Profile Image"/>
      <input placeholder="Type some emojis" className="bg-transparent outline-none w-full" />
    </div>
  )
}

type PostWithUser = RouterOutputs["posts"]["getAll"][number]

const PostView = (props: PostWithUser) => {
  const { post, author } = props

  return (
    <div className="flex gap-3 p-4 border-b border-slate-400">
      <Image src={author?.profileImageUrl} alt="User Image" width={50} height={50} className=" rounded-full"/>
      <div>
        <h1 className="text-xs text-gray-600">{author.username}</h1>
        <h1 className="text-sm">{post.content}</h1>
      </div>
    </div>
  )
}


const Home: NextPage = () => {
  const user = useUser()
  const { data, isLoading } = api.posts.getAll.useQuery()
  if (isLoading) return <h1>Loading...</h1>

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="w-full md:max-w-2xl border-x border-slate-200">
          <div className="border-b border-slate-400">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreatePostWizard />}
            <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
          </div>
          <div className="flex flex-col">
            {data?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id}/>
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
